### ISSUE TITLE
Closed Polls User Experience and Messaging Consistency Issues

### ISSUE THREAD

**Issue by Nantawat6510545543** [D7NAMITE/ku-polls#47]
1. Accessibility Issue:
Users can access voting pages for polls that have already closed, leading to potential confusion regarding a poll's status.

2. Inconsistent Closed Poll Notifications:
There's a discrepancy in how closed poll notifications are presented. When users access the results page from the index, no messages are shown, but if they enter from the details page, a message appears.

3. Error Message When Returning via Closed Poll:
An error message occurs when users return to the index page through a closed poll. (This error may not affect users if there can't access the voting page.)

4. Duplicate Error Messages during Voting Attempts:
When submitting a vote for a poll that disallows voting, three error messages may appear, with two of them being redundant. (This issue may not affect users if there can't access the voting page.)

![image](https://github.com/D7NAMITE/ku-polls/assets/114897362/ac3370d4-b575-455b-828b-26d9b460dda0)

**Comment by D7NAMITE** [comment]
From our discussion,
The problem could be fixed by restricting the accessibility of the closed polls.
We might need a further discussion on the testing of the error message.
I'll look back on the suggestion, Thank for the suggestion.

**Comment by D7NAMITE** [comment]
I've fixed this problem in the pull request issue#49. When the poll is not available the user won't have access to the poll detail page. However, it will replace the link to the voting page with "Poll Closed"

![issue49](https://github.com/D7NAMITE/ku-polls/assets/33195267/606f7665-d79c-4056-ae89-1775fe854042)
