### ISSUE TITLE
Login Error on Index Page

### ISSUE THREAD

**Issue by Nantawat6510545543** [D7NAMITE/ku-polls#48]
When a user successfully logs in, error messages are erroneously displayed on the index page. This could potentially bewilder users, as error messages should not be presented after a successful login. This issue occurs exclusively when accessing the login URL at 127.0.0.1:8000/accounts/login/?next=/polls/{question.id}/vote/.

**Comment by D7NAMITE** [comment]
From our discussion,
when the user isn't authenticated and gets in the vote, if the user tries to vote, it will send the user to login. When the user authenticates and routes back to the poll, the error message appears, indicating to the user that they haven't selected the choice yet.
Your suggestion included using the method `request.META.get(”HTTP_REFERER”)` in a vote to check if the previous page is the login page. This will be used to prevent the error message from occurring.
I'll revise this suggestion later. Thanks for your suggestion.

**Comment by D7NAMITE** [comment]
I've added the following:
I've implemented the request.META.get('HTTP_REFERER') to retrieve and check if the last page is the login page. To render the alternative detail page without the "You didn't select a choice." error message.
