### ISSUE TITLE
Button Bug in Details Page

### ISSUE THREAD

**Issue by Nantawat6510545543** [D7NAMITE/ku-polls#49]
Clicking on any edge button, even if it isn't a voting button, results in votes being sent. This can lead to unintentional voting by users.

**Comment by D7NAMITE** [comment]
From our discussion, the other buttons(other than vote-related) seem to interfere with the voting. You suggest that I should avoid using the same element with the voting input.
I will revise this suggestion later. Thank you for the recommendation.

**Comment by D7NAMITE** [comment]
I've fixed the problem as follows:
I've moved the navigation button included: result and back to the polls page to the navigation bar. Now, users can navigate from the detail pages to other pages using the nav bar on the top.
